### ISSUE TITLE
ipfs.add is not a function

### ISSUE THREAD

**Issue by chpio** [ipfs/js-ipfs-api#301]
im on *v6.0.1*

**Comment by harlantwood** [comment]
I'm getting the same issue.  worked fine on 4.1.0, but missing in 6.0.1.

Also seems to be missing from the API docs: https://github.com/ipfs/js-ipfs-api/blob/master/API.md .  In the API docs there is an `add` within `Extensions`, though its `tests` link points to a page that does not exist: https://github.com/ipfs/js-ipfs-api/blob/master/test/api/add.spec.js

**Comment by harlantwood** [comment]
Narrow version range: add works in 4.1.1, missing in 5.0.1

**Comment by harlantwood** [comment]
Maybe related to #279

**Comment by nginnever** [comment]
Hey @harlantwood!

We did change the way ```add``` is interfaced as you see in #279 

noffle added an alias <a href="https://github.com/ipfs/js-ipfs-api/blob/master/src/load-commands.js#L27">here</a> but it's not working. Going to look into it

**Comment by nginnever** [comment]
Opened a <a href="https://github.com/ipfs/js-ipfs-api/pull/309">PR</a> that will allow people to call add with or without files until the namespaces are ironed out.

**Comment by harlantwood** [comment]
Thanks @nginnever!

**Comment by diasdavid** [comment]
Fixed on https://github.com/ipfs/js-ipfs-api/pull/309. Reopen as necessary.

Thank you @nginnever :)
